#!/bin/env bash

sudo mkdir /lib/mozilla
sudo mkdir /lib/mozilla/plugins
sudo mkdir /lib64/mozilla
sudo mkdir /lib64/mozilla/plugins
sudo mkdir /lib32/mozilla
sudo mkdir /lib32/mozilla/plugins

sudo cp * /lib/mozilla/plugins
sudo cp * /lib64/mozilla/plugins
sudo cp * /lib32/mozilla/plugins

sudo chmod 755 /lib/mozilla/plugins/libflashplayer.so
sudo chmod 755 /lib/mozilla/plugins/libpepflashplayer.so
sudo chmod 755 /lib/mozilla/plugins/manifest.json

sudo chmod 755 /lib64/mozilla/plugins/libflashplayer.so
sudo chmod 755 /lib64/mozilla/plugins/libpepflashplayer.so
sudo chmod 755 /lib64/mozilla/plugins/manifest.json

sudo chmod 755 /lib32/mozilla/plugins/libflashplayer.so
sudo chmod 755 /lib32/mozilla/plugins/libpepflashplayer.so
sudo chmod 755 /lib32/mozilla/plugins/manifest.json
